---
- name: debug my var
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    my_vars:
      - 1
      - 2
      - 3
    my_other_vars:
      - cat
      - dog
      - monkey
#    other_middle_name: Ben

  tasks:

    - name: show variable
      debug: 
        msg: "{{ middle_name | default(other_middle_name) | default('Talmage') }}"
